# Generated by Django 5.2.9 on 2026-01-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0004_lessonprogress_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("user", "lesson")},
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms_app.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="module",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms_app.module",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="enrollment",
        ),
    ]
