# Generated by Django 5.2.9 on 2026-02-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0006_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="student_slots",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
