# Generated by Django 5.2.9 on 2026-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0007_course_student_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(default="2 week", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
